### ISSUE TITLE
api请求不了

### ISSUE THREAD

**Issue by xhun2015** [alongL/srs_ingest_helper#1]
请求命令行就报错
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

**Comment by alongL** [comment]
reference:
https://github.com/yhirose/cpp-httplib#g

httplib's fault. gcc 4.8's regex is broken.

in centos7. you should:
yum install devtoolset-6

remember to enable gcc-6
scl enable devtoolset-6 bash
