### ISSUE TITLE
拉流能不能暂停

### ISSUE THREAD

**Issue by xhun2015** [alongL/srs_ingest_helper#2]
想请教下大佬，在采集过程中，能不能实现暂停，暂停后保持采集源的连接，但不获取视频流，也不推流，恢复后才继续获取流进行推流。前提是保持连接不断开，场景是这样的，源视频流 有时间防盗链时间鉴权，如果断开连接，再次请求就失效了。如果一直连接，并一直拉流，对带宽消耗又比较大。只需要保持连接，需要的时候恢复拉流。不知道这个想法ffmpeg是否能够实现。对ffmeg不熟悉，所以请教下大佬。感谢

**Comment by alongL** [comment]
我对ffmpeg也不熟悉。 修改ffmpeg我觉得是有一定难度的，里面好像比较复杂。
你这个需求我觉得一般可能没有现成的，需要自己开发一下。 
rtmp协议好像支持暂停拉流的。

**Comment by xhun2015** [comment]
我看到ffmpeg里面有av_read_pause(),我在想在ffmpeg.c监听键盘输入了’p‘按键就调用av_read_pause()，实现暂停拉流。但是在C++中（你的代码中），比如现在有10个正在执行的ffmpeg拉转推命令行，我如何向其中一个命令行发送键盘输入p呢？我没学过C++，望大佬指点下，感谢

**Comment by alongL** [comment]
这个没搞过。
