### ISSUE TITLE
只要你访问8086，就自动停止

### ISSUE THREAD

**Issue by 272909223** [alongL/srs_ingest_helper#3]
![image](https://user-images.githubusercontent.com/56434703/120259037-c1c21500-c2c5-11eb-9788-111e7dca09d7.png)
如上图
不管是Telnet，还是http，只要访问下8086，
就自动停止运行。是啥情况呢
大佬

**Comment by alongL** [comment]
这是gcc-4.8的锅，
https://github.com/yhirose/cpp-httplib#g
https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

解决方法是用比4.8更高版本的gcc.
https://blog.csdn.net/ncdx111/article/details/106047228

**Comment by 272909223** [comment]
确实是，已解决。
感谢

**Comment by iamsee** [comment]
@272909223 怎么解决的，需要重新编译吗，用发布的包不行
![image](https://user-images.githubusercontent.com/6944557/122572911-cd148f00-d080-11eb-85f0-013db98c9230.png)

**Comment by alongL** [comment]
> @272909223 怎么解决的，需要重新编译吗，用发布的包不行
可以重新编译一下试试。
